version: "3"
services:
  zookeeper:
    image: zookeeper:latest
    privileged: true
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOOKEEPER_CLIENT_PORT="2181"
      - ZOOKEEPER_TICK_TIME="2000"
    ports:
      - "2181:2181"
      - "7000:7000"
    networks:
      - kafka    
  kafka:
    image: kafka:latest
    privileged: true
    links:
      - "zookeeper:zookeeper" 
    ports:
      - "9092:9092"
      - "9093:9093"
      - "7071:7071"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper
    networks:
      - kafka      
  procons:
    image: procons:latest
    volumes:
      - ./Procons/:/itau/procons 
    networks: 
      - kafka
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./Prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - kafka     
networks:
    kafka:
      name: kafka