{
 "title": "Kafka",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Transações",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_log_log_value{name=\"LogEndOffset\" , topic = \"test-topic\" }) - sum(kafka_log_log_value{ name=\"LogStartOffset\", topic =\"test-topic\" })"
    }
   ]
  },
  {
   "title": "Kafka Broker Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "java_lang_runtime_uptime{instance=\"kafka:7071\",job=\"kafka\"}"
    }
   ]
  },
  {
   "title": "Topic BytesIn to BytesOut Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_oneminuterate{instance=\"kafka:7071\",job=\"kafka\",name=\"BytesInPerSec\",topic=\"test-topic\"}"
    },
    {
     "expr": "kafka_server_brokertopicmetrics_oneminuterate{instance=\"kafka:7071\",job=\"kafka\",name=\"BytesOutPerSec\",topic=\"test-topic\"}"
    }
   ]
  },
  {
   "title": "Network Processor Idle (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "kafka_network_processor_value{instance=\"kafka:7071\",job=\"kafka\",name=\"IdlePercent\"}"
    }
   ]
  },
  {
   "title": "JVM Heap Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "java_lang_memory_heapmemoryusage_used{instance=\"kafka:7071\",job=\"kafka\"}"
    }
   ]
  },
  {
   "title": "JVM System CPU Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "java_lang_operatingsystem_systemcpuload{instance=\"kafka:7071\",job=\"kafka\"}"
    }
   ]
  },
  {
   "title": "Request Handler Idle (%)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "kafka_server_kafkarequesthandlerpool_oneminuterate{instance=\"kafka:7071\",job=\"kafka\",name=\"RequestHandlerAvgIdlePercent\"}"
    }
   ]
  },
  {
   "title": "Kafka Network Request Metrics",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_oneminuterate{instance=\"kafka:7071\",job=\"kafka\",name=\"RequestsPerSec\"}"
    }
   ]
  },
  {
   "title": "Total Partition Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_server_replicamanager_value{instance=\"kafka:7071\",job=\"kafka\",name=\"PartitionCount\"}"
    }
   ]
  },
  {
   "title": "Total Under Replicated Partition Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_value{name=\"UnderReplicatedPartitions\"})"
    }
   ]
  },
  {
   "title": "Max lag in messages btw follower and leader replicas",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_replicafetchermanager_value{instance=\"kafka:7071\",job=\"kafka\",name=\"MaxLag\"}"
    }
   ]
  }
 ]
}